webpack/enhanced-resolve

lib/DirectoryDescriptionFileFieldAliasPlugin.js

Hi,
Alias resolution doesn't work on a symlink module.
I discovered this when i tried to use ```superagent```. This module uses the browser support in  ```package.json```:
```javascript
"browser": {
"./lib/node/index.js": "./lib/client.js",
"emitter": "component-emitter",
"reduce": "reduce-component"
},
"main": "./lib/node/index.js",
```
When I install it with ```npm install``` it's Ok but when I want to use it as global dependency (```npm install -g superagent``` and ```npm link``` in my module folder), I see that the main file used is no longer aliased to ```./lib/client.js```
After some research I found that ```DirectoryDescriptionFileFieldAliasPlugin.js``` has an issue when ```request.path``` is modified by ```ResultSymlinkPlugin.js```
I tried to resolve this with this pull request …

Fix alias resolution when symlink is used

---

lib/UnsafeCachePlugin.js
test/unsafe-cache.js

Including the query in the cacheId means it will not return if the queries are different, I believe fixing the issue here: https://github.com/webpack/webpack/issues/1940

Include query when caching webpack-bug #1940

---

lib/ResolverFactory.js

If you set `options.resolve.plugins` to anything, even an empty array, `enhanced-resolve` will start behaving weirdly. By weirdly I mean that it will duplicate some plugins in the list of plugins. If we, for example, use a mock `HelloHello` plugin in our webpack config, e.g. 
```
resolve: { 
plugins: [new HelloHello()] 
}
```
, when `WebpackOptionsApply` is producing the `Resolvers` using the `ResolverFactory`, it will think all of the plugins from the `normal` resolver are external plugins for the `context` resolver (https://github.com/webpack/webpack/blob/e896d14829d0afc75c8510862afbe3c8e06d67d8/lib/WebpackOptionsApply.js#L277-L283). 
Example:
```
Number of plugins: 32 (normal resolvers)    49 (context resolvers)
HelloHello                                  HelloHello
UnsafeCachePlugin …
```

Create a shallow copy of options.plugins, instead of referring to the original array

---

lib/ResolverFactory.js

This PR will fix the resolving of multiple defined `descriptionFiles`.
Given a Webpack config of:
``` js
resolve: {
descriptionFiles: ['package.json', 'bower.json']
}
```
Only `package.json` will be searched for (unknown reason). This PR will search for all defined `descriptionFiles`.

Fix resolving of DescriptionFiles

---

lib/CachedInputFileSystem.js

It was just missing actually return the parsed JSON content.
It was affecting the reading of description files (`package.json`), leaving the content as `undefined`. Like this:
```
descriptionFilePath: '[...]/node_modules/react-router/package.json',
descriptionFileData: undefined,
descriptionFileRoot: '[...]/node_modules/react-router',
```
This PR also fixes https://github.com/benmosher/eslint-plugin-import/issues/688#issuecomment-267343188

Fix `_readJsonSync` in CachedInputFileSystem

---

lib/AliasPlugin.js
lib/getPaths.js

`getPaths.js`: updated to fix lint rule so tests pass
`AliasPlugin.js`: changed the call to `indexOf` to use a [modified polyfill](https://github.com/mathiasbynens/String.prototype.startsWith/blob/master/startswith.js) for `String.prototype.startsWith`. In our Webpack build these calls to `indexOf` account for about 12% of total execution time. Turns out v8's implementation isn't written in JavaScript (see [string.js](https://github.com/v8/v8/blob/master/src/js/string.js) which instead calls out to `%StringIndexOf` - v8's way of linking to its C++ code). This jump from JS land to C++ is such a large performance hit that much of v8's JavaScript built-ins are written in JS instead of the faster, compiled C++. I also flipped the execution order of the test cases on both lines from `search() …

Use optimized string searching for faster alias resolving

---

lib/ParsePlugin.js

When upgrading to latest Webpack, I got some errors related to parsed being undefined, so this fix is a tentative one.

Fix undefined parsed.module or parsed.directory issue

---

lib/Resolver.js

tl;dr - this change shaves ~2.5 min off our longest webpack build at Redfin.
We've been putting off upgrading off webpack v1 for awhile, because when we tried to upgrade from webpack1 to v2/v3, our build perf took a big hit. We found/fixed a couple issues, but we were still looking at an increase from ~1:45 webpack build with v1 to ~4.5+ min with webpack v3 (v2 was even worse -- 5+ minutes)
I couldn't sleep, so I dug in with a profiler+console.log again, and noticed that `CachedInputFileSystem.readlink` was getting called with _all_ values of `module.extensions`, even when the file extension was specified on the require, or was the first extension in the list. For us, that's a _lot_ of calls! I originally tried removing removing some unnecessary module.extensions (we were using webpack 1 …

[Proposal] Performance: Make file resolving asyncSeriesBail instead of parallel

---

lib/CachedInputFileSystem.js
test/CachedInputFileSystem.js

Do not cache results for non-string names

---

lib/ResolverFactory.js

Support for sub-arrays in mainFields (i.e. using an object in package.json to determine the main file to use for a module) seems to have been accidentally not included in enhanced-resolve.  This commit re-adds it.  Huge thanks to @sokra for the fix.
Tested by using this version of enhanced-resolve in https://github.com/sjbarag/webpack-mwe .  The test case in that MWE now passes.
fixes #116

Restore support for sub-arrays in mainFields

---

package.json

Fix for #130
Adds the LICENSE file during `npm pack` and `npm publish`.

Add LICENSE file to npm releases

---

package.json

Drops node engine version down, and confirms build/test against node 6.9.0.
This resolves issue #141, which in-turn will enable https://github.com/webpack/webpack/issues/6579 to be resolved.

Drop node engine down to 6.9.0 to support AWS lambda environments.

---

declarations.d.ts
lib/CachedInputFileSystem.js
lib/Resolver.js
test/CachedInputFileSystem.js
test/pr-53.js
tsconfig.json
types.d.ts

add sync mode (when only using sync fs operations)
checks cache invalidation based on Date.now()
fixes #229
async mode is entered once an async fs operation is used
checks cache invalidation based on a timeout
after the timeout it falls back to the sync mode
add separate backend for zero duration without caching (only merges operations)
add support for optional options argument of filesystem operations (uncached)
update typings

refactor CachedFileSystem

---

lib/PnpPlugin.js
lib/ResolverFactory.js
test/fixtures/pnp-a/m2/a.js
test/pnp.js

fallback to other alternatives when PnP reports an undeclared dependency
fixes vercel/next.js#16892

resolve PnP at the location of node_modules in the modules option

---

lib/ResolverFactory.js
test/exportsField.js
test/importsField.js

* exports and imports field continue resolving extensions, directories and aliases if fullySpecified is not specified
* load description file after resolving with exports or imports field 
fixes #256
fixes https://github.com/webpack/webpack/issues/11750

exports and imports field fixes

---

lib/CachedInputFileSystem.js
lib/Resolver.js
lib/ResolverFactory.js
lib/util/process-browser.js
package.json
types.d.ts
yarn.lock

Allow `enhanced-resolve/lib/ResolverFactory.js` to be bundled for the browser.
After this change the the only requirement for browser bundling is node's `path` package which is reasonable.

Minimize footprint for browser bundling

---

lib/util/process-browser.js

Fix browser bundling of the `process-browser.js` since it used as `require('process').versions` so the module itself is exported and not `process` as a key

fix: process-browser.js

---

lib/ResolverFactory.js
test/pnp.js

Fixes https://github.com/webpack/enhanced-resolve/issues/288.
Ideally, node_modules should not even be considered if the pnp api is enabled, however it looks like that's intentional according to https://github.com/webpack/enhanced-resolve/issues/273

fix: give precedence to pnp over node_modules, close #288

---

lib/ResolverFactory.js
test/extensions.js

enforceExtension should default to true when extensions contain empty string
requested by @sokra to complement webpack pull request:
feat: accept empty string in config.resolve.extensions
https://github.com/webpack/webpack/pull/12613
- tests added
- no conflict with existing tests
- no conflict with webpack

feature: enforceExtension when extensions contain empty string

---

lib/getInnerRequest.js
test/fixtures/browser-module/package.json

fix bug when aliasing `.`

---

.github/workflows/test.yml

Use the built-in action/cache for Yarn deps in CI

ci: use setup-node cache for Yarn

---

README.md
lib/ExtensionAliasPlugin.js
lib/ResolverFactory.js
test/extension-alias.js
types.d.ts

add new option extensionAlias which maps extension to extension alias
related to https://github.com/TypeStrong/ts-loader/issues/1383#issuecomment-968075478

add extension alias

---

lib/Resolver.js

The error message was referring to the `path` argument being not a string while it was the `request` argument being not a string.

Fix argument name in error message

---

lib/DirectoryExistsPlugin.js
lib/FileExistsPlugin.js
lib/ModulesInHierarchicalDirectoriesPlugin.js
lib/Resolver.js
package.json
types.d.ts
yarn.lock

Resolves https://github.com/webpack/enhanced-resolve/issues/316
Additionally fixing a few types and updating graceful-fs to support the new option. Thankfully, `stat` being null (vs throwing) is already being handled correctly.
cc @alexander-akait - graceful-fs has been updated now so this is unblocked

perf: utilize throwIfNoEntry in sync mode

---

lib/Resolver.js
types.d.ts

This pr is from #16780 in the webpack repository. [#16780](https://github.com/webpack/webpack/issues/16780)
The relevant unit tests have been run, and types.d.ts have been automatically generated. Please pr this
This is my first attempt to resolve issues in webpack. If there are any issues that do not meet the specification, I will modify them as soon as possible. 😄
Results of running unit tests locally:

feat: add withFileTypes in FileSystem

---

README.md

Fixes #358  by just documenting the actual default, rather than introducing a breaking change

chore: update readme to reflect conditionNames default

---

lib/Resolver.js
lib/index.js
test/resolve.js
test/simple.js
test/symlink.js
types.d.ts

fixes #356 
i need some help with the overloads here i think.
you can see the strong types now mean a bunch of tests need to cast things too... im not sure there's a clean way to type the callback function strongly and not have to do those casts. the compiler is right: the result could be undefined if there's an error.

fix: improve typescript defs

---

.github/workflows/test.yml

Update GitHub actions to use latest versions

chore: update `checkout`, `setup-node`, and `codecov` github actions

---

lib/AliasPlugin.js
lib/DescriptionFilePlugin.js
lib/DescriptionFileUtils.js
lib/Resolver.js
lib/ResolverFactory.js
lib/getPaths.js
tooling/format-file-header.js

This PR contains a:
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None

chore: replace deprecated String.prototype.substr()

---

.cspell.json
README.md

docs: add badges in README

---

package.json

Since it is now being run on all files, it can be run as part of the pre-commit hook to check locally

chore: add cSpell commit hook

---

lib/ResolverFactory.js
test/plugins.test.js
types.d.ts

Part of https://github.com/webpack/webpack-cli/issues/3836
Allow to use:
```js
// `false` value for an example, for example when you are in development mode and don't want to use plugin
// so you don't need to use `.filter(Boolean)`, it is faster and has a better DX
const isProduction = false; 
module.exports = {
//...
resolve: {
plugins: [
isProduction && new DirectoryNamedWebpackPlugin()
],
},
};
```
Note - you an use any `falsy` values, `NaN` is `falsy` too, but https://github.com/Microsoft/TypeScript/issues/15135, and I don't think it is a good idea allow to pass `NaN`

feat: ignore `false`/`null`/`undefined` plugins

---

lib/PnpPlugin.js
lib/ResolverFactory.js
lib/util/module-browser.js
package.json
test/pnp.test.js
types.d.ts

**What's the problem this PR addresses?**
- In some cases `enhanced-resolve` is outside the control of the `pnpapi` and can't require it
- The `issuer` might not belong to the same `pnpapi` as `enhanced-resolve`
- The `issuer` might not belong to a `pnpapi` at all and should use the `node_modules` resolution instead
Fixes https://github.com/arcanis/pnp-webpack-plugin/issues/32 for Webpack 5
**How did you fix it?**
Use `module.findPnpApi` to locate the correct `pnpapi` for the `issuer`, if a `pnpapi` isn't found continue the normal resolution

fix: find the `pnpapi` the `issuer` belongs to

---

lib/CachedInputFileSystem.js
test/CachedInputFileSystem.test.js
test/pr-53.test.js
types.d.ts

fixes https://github.com/webpack/enhanced-resolve/issues/367
Also we have bug here, because real fs allows to pass URL and Buffer, not only string, we need to fix it

fix: types for cached input filesystem

---

.github/workflows/test.yml
lib/ExportsFieldPlugin.js
lib/ImportsFieldPlugin.js

/cc @vankop Do you know why we use `path` here instead our cachable version?
We can improve perf just using it

fix: use cache for exports and imports plugins

---

lib/util/entrypoints.js
test/exportsField.test.js
test/importsField.test.js

This aligns the "default" condition behaviour with Node.Js. Specifically, this allows the "default" condition to be found anywhere in the "exports" without throwing an error.
- https://github.com/webpack/enhanced-resolve/issues/421
- https://github.com/eslint-community/eslint-plugin-n/issues/242
- https://github.com/oxc-project/oxc-resolver/issues/160
---
fixes #421

feat: allow default condition to be anywhere

---

lib/Resolver.js

This is a minor optimization that avoids allocating immediately dereferenced arrays when creating a new stack inside `doResolve`. In the build that I'm testing against, this is called >750k times, which means that we're allocating ~32mb of array data to the heap that's then spent in GC.
It's hard to find optimizations in webpack's codebase, but from my debugging we're spending more time in GC than in any other function.
Here's a jsperf comparing these two ways of creating a one item set:
https://jsperf.app/vureri 
And a screenshot of the output for me:

Avoid creating a new array inside doResolve.

---

lib/AliasPlugin.js
test/alias.test.js

Closes https://github.com/webpack/webpack/pull/19075
add wildcards pattern
```javascript
"@*": ["./src/*"]
```

feat: add wildcards

---

lib/util/identifier.js
test/identifier.test.js

Adds a fast path to `parseIdentifier` that avoids the overhead of regex processing when the input does not contain a null character. Improves performance of `parseIdentifier` by ~75% for typical usage on NodeJS 18.19.1.
Before:
After:
Adds additional unit tests to `parseIdentifier` for NULL-escaped strings.

feat: parseIdentifier fast path for requests without \0

---

lib/index.js
types.d.ts

Fix #447
I also exported `BaseFileSystem` since it is widely used in the `CachedInputFileSystem` class.

feat: export type SyncFileSystem and type BaseFileSystem

---

lib/AliasFieldPlugin.js
lib/AliasPlugin.js
lib/DescriptionFilePlugin.js
lib/DescriptionFileUtils.js
lib/LogInfoPlugin.js
lib/Resolver.js
package.json
test/missing.test.js
types.d.ts

After upgrading to Webpack ^5.100.0 (https://github.com/lynx-family/lynx-stack/pull/1418), we got errors related with types:
```
- JsonObjectTypes[key]: string & Array<JsonValueTypes>
- nonsensible intersection
- JsonObjectTypes[key]: number & Array<JsonValueTypes>
- nonsensible intersection
- JsonObjectTypes[key]: false & Array<JsonValueTypes>
- nonsensible intersection
- JsonObjectTypes[key]: true & Array<JsonValueTypes>
- nonsensible intersection
```
See: https://github.com/lynx-family/lynx-stack/actions/runs/16744114403/job/47401398078

fix: nonsensible intersection
