- lib/NodeJsInputFileSystem.js
- lib/SyncNodeJsInputFileSystem.js
to resolve https://github.com/webpack/webpack/pull/1227
> normalize filenames to nfc when readdir

- lib/Resolver.js
> Memoize calls to memory-fs join

- README.md
I've pulled some documentation from code to the README
> Added some docs for createResolver(options)

- lib/ResolverFactory.js
Resolves #50 - pretty minor I know but every little helps I guess? 😄
> Updated ResolverFactory.js to remove unused requires

- lib/Resolver.js
- test/missing.js
Fixes #88 
ping @TheLarkInn @sokra would love some input cc @gdborton
> RFC: perform resolution without logging and re-run with logging when failing.

- package.json
Required to get enhanced-resolve to work independently.
> Upgrade tapable version

- README.md
Also made a few small other opinionated additions or modifications.
> Add basic usage example and plugin example to README.md

- lib/AliasPlugin.js
- lib/ResolverFactory.js
to avoid deep call stacks
fixes #120
> handle many aliases per plugin

- LICENSE
> #126: added LICENSE file

- README.md
1. Sort options follow the [document](https://webpack.js.org/configuration/resolve).
2. Added option `symlinks` from the [code](https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L75).
> sort options & added symlinks

- README.md
When I use the demo code, I got an deprecated warning message.
https://github.com/webpack/enhanced-resolve/blob/master/lib/Resolver.js#L139
> added resolveContext

- README.md
Updating the outdated plugin boilerplate in README.md
> Update the plugin boilerplate in README

- lib/Resolver.js
- lib/createInnerCallback.js
> Add more info in the deprecation warnings

- .gitignore
> gitignore .idea .vscode .DS_Store

- lib/AliasPlugin.js
- lib/ResolverFactory.js
- test/alias.js
allows
``` js
alias: {
something: false
}
```
> add support for "false" alias

- lib/Resolver.js
- lib/ResolverFactory.js
- lib/SyncAsyncFileSystemDecorator.js
- lib/forEachBail.js
- package.json
- test/forEachBail.js
- test/missing.js
- tsconfig.json
- yarn.lock
https://github.com/webpack/enhanced-resolve/issues/184
**What kind of change does this PR introduce?**
typescript linting for source code and tests
**Did you add tests for your changes?**
No
**Does this PR introduce a breaking change?**
No 
**What needs to be documented once your changes are merged?**
Nothing
> Linting with typescript

- .eslintrc.js
- package.json
- yarn.lock
Enforcing rule `jsdoc/require-hyphen-before-param-description` 
https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-hyphen-before-param-description
**What kind of change does this PR introduce?**
feature
**Did you add tests for your changes?**
No
**Does this PR introduce a breaking change?**
No
**What needs to be documented once your changes are merged?**
Nothing
> enforce eslint require-hyphen-before-param-description

- lib/Resolver.js
https://github.com/webpack/enhanced-resolve/issues/184
What kind of change does this PR introduce?
esdoc `resolveContext`. Required for typization of resolver plugins.
Did you add tests for your changes?
N/A
Does this PR introduce a breaking change?
no
What needs to be documented once your changes are merged?
nothing
> esdoc resolve context

- lib/AliasFieldPlugin.js
- lib/AliasPlugin.js
- lib/AppendPlugin.js
- lib/CachedInputFileSystem.js
- lib/DescriptionFilePlugin.js
- lib/DirectoryExistsPlugin.js
- lib/FileExistsPlugin.js
- lib/FileKindPlugin.js
- lib/JoinRequestPartPlugin.js
- lib/JoinRequestPlugin.js
- lib/MainFieldPlugin.js
- lib/ModuleKindPlugin.js
- lib/ModulesInHierachicDirectoriesPlugin.js
- lib/ModulesInRootPlugin.js
- lib/NextPlugin.js
- lib/ParsePlugin.js
- lib/PnpPlugin.js
- lib/Resolver.js
- lib/ResolverFactory.js
- lib/ResultPlugin.js
- lib/SymlinkPlugin.js
- lib/TryNextPlugin.js
- lib/UnsafeCachePlugin.js
- lib/UseFilePlugin.js
- test/pnp.js
- test/symlink.js
- tsconfig.json
https://github.com/webpack/enhanced-resolve/issues/184
**What kind of change does this PR introduce?**
esdoc, enable strictNullChecks in tsconfig
**Did you add tests for your changes?**
No
**Does this PR introduce a breaking change?**
No
**What needs to be documented once your changes are merged?**
Nothing
> esdoc ResolverFactory, enable strictNullChecks in tsconfig

- package.json
> fix: reflect license on npmjs.com

- .eslintrc.js
- .prettierrc.js
- .travis.yml
- lib/ResolverFactory.js
- lib/index.js
- package.json
- test/CachedInputFileSystem.js
- test/alias.js
- test/browserField.js
- test/dependencies.js
- test/extensions.js
- test/forEachBail.js
- test/missing.js
- test/plugins.js
- test/pnp.js
- test/pr-53.js
- test/resolve.js
- test/simple.js
- test/symlink.js
- test/unsafe-cache.js
- tsconfig.types.json
- types.d.ts
- yarn.lock
add special tooling
generate typings
cleanup test files
test typings with test suite
> add special tooling

- lib/processExportsField.js
- test/exportsField.js
What kind of change does this PR introduce?
handle syntax sugar for conditional mapping
Did you add tests for your changes?
yes
Does this PR introduce a breaking change?
yes
What needs to be documented once your changes are merged?
None
> handle syntax sugar for conditional mapping

- README.md
- lib/DescriptionFileUtils.js
- lib/ExportsFieldPlugin.js
- lib/MainFieldPlugin.js
- lib/ResolverFactory.js
- lib/SelfReferencePlugin.js
- lib/index.js
- test/exportsField.js
- test/fixtures/exports-field3/node_modules/exports-field/main.js
- test/fixtures/exports-field3/node_modules/exports-field/package.json
- types.d.ts
- improve docs
- support exportsFields configuration param
> exportsFields option

- lib/ExportsFieldPlugin.js
- lib/index.js
- test/exportsField.js
- types.d.ts
- add exports field test cases
- add types export
> support query in ExportsFieldPlugin

- lib/forEachBail.js
Simplify and improve the readability of the code.
> refactor forEachBail.js

- lib/util/identifier.js
- test/identifier.js
I didn't work out as expected. Especially with directory paths used with webpack context
> revert #folder handling

- lib/CachedInputFileSystem.js
- test/CachedInputFileSystem.js
Fixes https://github.com/webpack/webpack/issues/11518
> avoid stack overflow due to cached resolving

- README.md
- lib/ResolverFactory.js
- test/resolve.js
- types.d.ts
> add preferRelative option

- README.md
- lib/ParsePlugin.js
- lib/Resolver.js
- lib/util/identifier.js
- test/resolve.js
allow escaping in requests
when path or query contains # it will be escaped
> resolve folders which look like a fragment

- lib/CachedInputFileSystem.js
- test/CachedInputFileSystem.js
fixes https://github.com/webpack/webpack-cli/issues/1985
> fix problem where callback is called twice

- lib/PnpPlugin.js
- test/pnp.js
fixes https://github.com/webpack/webpack/issues/12093
> remove fullySpecified when resolving a module request with PnP

- lib/PnpPlugin.js
- lib/ResolverFactory.js
- test/fixtures/pnp/pkg3/a.js
- test/fixtures/pnp/pkg3/package.json
- test/pnp.js
> handle exports field when using PnP

- README.md
- lib/ResolverFactory.js
- test/roots.js
> add preferAbsolute option to prefer absolute paths over roots

- lib/util/entrypoints.js
- test/exportsField.js
fix a few bugs in exports/imports handling
> add support for wildcard exports/imports mapping

- lib/PnpPlugin.js
- lib/Resolver.js
- lib/ResolverFactory.js
- package.json
- tsconfig.types.json
- types.d.ts
- yarn.lock
> use typescript 4.2

- lib/ImportsFieldPlugin.js
- test/importsField.js
> allow to resolve imports from a subpath

- lib/Resolver.js
- lib/ResultPlugin.js
- lib/createInnerContext.js
- lib/getPaths.js
- test/getPaths.js
- test/yield.js
- types.d.ts
- If `resolveContext.yield` presented will return resolve results there `resolveContext.yield(obj)`.
- In this case resolve callback will not return any result.
- If no result yielded error with log will be returned as always.
> add yield in resolve context

- .github/workflows/test.yml
Add node v16 and node v17 in CI.
/cc @alexander-akait
> chore: add node v16 and node v17 in CI

- lib/AliasFieldPlugin.js
- test/browserField.js
- test/fixtures/browser-module/package.json
prevent checking object prototype properties
fixes #118
> use only alias field properties

- lib/AliasPlugin.js
- test/alias.js
> fix hash aliases

- lib/ExportsFieldPlugin.js
- lib/ImportsFieldPlugin.js
- lib/util/path.js
- test/exportsField.js
- test/fixtures/exports-field-error/node_modules/exports-field/package.json
- test/importsField.js
- test/path.js
- throw error in imports field if trying to access out of package scope
- fix utility function `checkImportsExportsFieldTarget`
fixes #346
> fix imports field

- lib/DirectoryExistsPlugin.js
- lib/FileExistsPlugin.js
- lib/ModulesInHierarchicalDirectoriesPlugin.js
- lib/Resolver.js
- package.json
- types.d.ts
- yarn.lock
fixes: https://github.com/webpack/enhanced-resolve/issues/362
This reverts commit 96be62de9ca9cd1fd6f79f0036a3cf5c3a6ef0b7.
> Revert "perf: utilize throwIfNoEntry in sync mode"

- .github/workflows/test.yml
> ci: add Node.js v23
